on: 
  push:
    branches: [ main ]
  pull_request:
    types: 
      - closed
    branches: [ main ]
  
name: Create test coverage badge
jobs:
  if-merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Make code coverage badge
        uses: timkrase/phpunit-coverage-badge@v1.2.1
        with:
          github_token: ${ secrets.GITHUB_TOKEN }
          coverage_badge_path: output/coverage.svg
          push_badge: true
